version: '2.4'
services:
  caddy:
    image: ihciah/caddy:latest
    container_name: caddy
    restart: always
    network_mode: "host"
    volumes:
      - type: "bind"
        source: "./Caddyfile"
        target: "/etc/caddy/Caddyfile"
      - "./data:/data/caddy"
      - "./config:/config"
